import Head from 'next/head'

import Layout from '@components/Layout/Layout'


const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Tag Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Layout>

     </Layout>
    </>
  )
}

export default Home;
